Missing hint
contao/skeleton-bundle pull request #13
Opened 2023-02-10 20:58 UTC by Ernestopheles

Without this hint newbies like me ;-)) might wonder why the tools are not working...

2023-05-04 06:50 UTC, aschempp requested changes

2023-05-04 06:50 UTC, aschempp commented on README.md
>  Run the PHP-CS-Fixer and the unit test before you release your bundle:
```suggestion
First make sure the tools are installed and up to date by running `composer bin all update` in your bundle's root.
Then run the PHP-CS-Fixer and the unit test before you release your bundle:
```

2023-05-11 06:09 UTC, aschempp approved these changes

2024-02-15 17:47 UTC, fritzmg approved these changes
@leofeyer this should be merged imho

2024-02-16 16:49 UTC, leofeyer commented on README.md
> +Then run the PHP-CS-Fixer and the unit test before you release your bundle:
```suggestion
First make sure the tools are installed and up to date by running
`composer bin all update` in your bundle's root. Then run the PHP-CS-Fixer and
the unit test before you release your bundle:
```

2024-03-07 14:21 UTC, merged

2024-03-07 14:21 UTC, leofeyer commented
Thank you @Ernestopheles.